[package]
name = "sp"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
base64 = "0.22.1"
dotenvy = "0.15.7"
openssl = "0.10.73"
openssl-probe = "0.1.6"
reqwest = "0.12.22"
samael = { version = "0.0.19", features = ["xmlsec"] }
tokio = { version = "1.47.0", features = ["full"] }
